export const ALL_PERMISSIONS = {
    COMPANIES: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/companies', module: "COMPANIES" },
        CREATE: { method: "POST", apiPath: '/api/v1/companies', module: "COMPANIES" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/companies', module: "COMPANIES" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/companies/{id}', module: "COMPANIES" },
    },
    JOBS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/jobs', module: "JOBS" },
        CREATE: { method: "POST", apiPath: '/api/v1/jobs', module: "JOBS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/jobs', module: "JOBS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/jobs/{id}', module: "JOBS" },
    },
    PERMISSIONS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/permissions', module: "PERMISSIONS" },
        CREATE: { method: "POST", apiPath: '/api/v1/permissions', module: "PERMISSIONS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/permissions', module: "PERMISSIONS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/permissions/{id}', module: "PERMISSIONS" },
    },
    RESUMES: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/resumes', module: "RESUMES" },
        CREATE: { method: "POST", apiPath: '/api/v1/resumes', module: "RESUMES" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/resumes', module: "RESUMES" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/resumes/{id}', module: "RESUMES" },
    },
    ROLES: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/roles', module: "ROLES" },
        CREATE: { method: "POST", apiPath: '/api/v1/roles', module: "ROLES" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/roles', module: "ROLES" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/roles/{id}', module: "ROLES" },
    },
    USERS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/users', module: "USERS" },
        CREATE: { method: "POST", apiPath: '/api/v1/users', module: "USERS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/users', module: "USERS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/users/{id}', module: "USERS" },
    },
    CHATS: {
        GET_CONVERSATIONS: { method: "GET", apiPath: '/api/v1/chat/conversations', module: "CHATS" },
        CREATE_CONVERSATION: { method: "POST", apiPath: '/api/v1/chat/conversations', module: "CHATS" },
        GET_CONVERSATION_BY_ID: { method: "GET", apiPath: '/api/v1/chat/conversations/{id}', module: "CHATS" },
        GET_MESSAGES: { method: "GET", apiPath: '/api/v1/chat/conversations/{id}/messages', module: "CHATS" },
        SEND_MESSAGE: { method: "POST", apiPath: '/api/v1/chat/messages', module: "CHATS" },
        MARK_READ: { method: "PATCH", apiPath: '/api/v1/chat/conversations/{id}/read', module: "CHATS" },
        GET_BADGE: { method: "GET", apiPath: '/api/v1/chat/badge', module: "CHATS" },
    },
    INTERVIEWS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/interviews', module: "INTERVIEWS" },
        CREATE: { method: "POST", apiPath: '/api/v1/interviews', module: "INTERVIEWS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/interviews', module: "INTERVIEWS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/interviews/{id}', module: "INTERVIEWS" },
        GET_BY_ID: { method: "GET", apiPath: '/api/v1/interviews/{id}', module: "INTERVIEWS" },
        CANDIDATE_RESPOND: { method: "PATCH", apiPath: '/api/v1/interviews/candidate-respond', module: "INTERVIEWS" },
    },
}